# Schema for the configuration files of the easydb module.
easydb.settings:
  type: config_object
  label: 'easydb module settings'
  mapping:
    easydb_server_url:
      type: string
      label: 'easydb server URL'
    easydb_files_subdir:
      type: string
      label: 'easydb files sub-directory'
    language_mapping:
      type: sequence
      label: 'Language mapping'
      sequence:
        type: string
